#!/bin/sh

ln -s -f /opt/apps/dde-dock-graphics-plugin/files/plugins/libswitch-graphics-card.so /usr/lib/dde-dock/plugins/libswitch_graphics_card.so

ln -s -f /opt/apps/dde-dock-graphics-plugin/files/share/pkexec/com.deepin.pkexec.dde-dock-graphics-plugin.policy /usr/share/polkit-1/actions/com.deepin.pkexec.dde-dock-graphics-plugin.policy
